package com.aaryo.selfattendance.utils

import android.content.Context
import android.content.Intent
import android.net.Uri
import com.aaryo.selfattendance.data.model.Attendance
import java.time.YearMonth
import java.time.format.TextStyle
import java.util.Locale

object WhatsAppShare {

    /**
     * Share monthly attendance summary via WhatsApp (or any app if WA not installed).
     */
    fun shareMonthlyReport(
        context: Context,
        records: List<Attendance>,
        month: YearMonth,
        userName: String,
        estimatedSalary: Double
    ) {
        val monthName = month.month.getDisplayName(TextStyle.FULL, Locale.getDefault())
        val year = month.year

        val present  = records.count { it.status == "PRESENT" }
        val half     = records.count { it.status == "HALF" || it.status == "HALF_DAY" }
        val holiday  = records.count { it.status == "HOLIDAY" }
        val absent   = records.count { it.status == "ABSENT" }
        val overtime = records.sumOf { it.overtimeHours }
        val total = records.size
        val rate = if (total > 0) ((present + holiday + half * 0.5) / total * 100).toInt() else 0

        val emoji = when {
            rate >= 95 -> "🏆"
            rate >= 80 -> "✅"
            rate >= 60 -> "👍"
            else       -> "📊"
        }

        val text = buildString {
            appendLine("$emoji *$monthName $year — Attendance Report*")
            appendLine("👤 *$userName*")
            appendLine()
            appendLine("📋 *Summary*")
            appendLine("✅ Present:   $present days")
            appendLine("🌓 Half Day:  $half days")
            if (holiday > 0) appendLine("🎉 Holiday:   $holiday days")
            appendLine("❌ Absent:    $absent days")
            if (overtime > 0) appendLine("⏱️ Overtime:  ${"%.1f".format(overtime)} hrs")
            appendLine()
            appendLine("📈 Attendance Rate: *$rate%*")
            if (estimatedSalary > 0) {
                appendLine("💰 Estimated Salary: *₹${"%.0f".format(estimatedSalary)}*")
            }
            appendLine()
            appendLine("_Generated by Self Attendance Pro_ 📱")
        }

        // Try WhatsApp first, fall back to any share target
        val whatsappIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            `package` = "com.whatsapp"
        }

        val fallbackIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
        }

        try {
            context.startActivity(whatsappIntent)
        } catch (_: Exception) {
            context.startActivity(Intent.createChooser(fallbackIntent, "Share via"))
        }
    }

    fun isWhatsAppInstalled(context: Context): Boolean {
        return try {
            context.packageManager.getPackageInfo("com.whatsapp", 0)
            true
        } catch (_: Exception) { false }
    }
}
